### PR TITLE
Add ReplicaAutoBalance param for StorageClass

### PR DESCRIPTION
**Pull request by MioOgbeni**
Hi, I would like to add possibility to configure ReplicaAutoBalance parameter for StorageClass definition.

Signed-off-by: Tomáš Novák <tomas.novak@bcas.cz>

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@longhorn/qa Could you help verify this PR? Thanks.

**Comment by MioOgbeni** [comment]
@c3y1huang Hi, can you review it? It's been almost 3 weeks since opening and still awaiting review.

**Review by c3y1huang — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
