### PR TITLE
Move CRDs into CRD folder as by helm RFC

### PR DESCRIPTION
**Pull request by EugenMayer**
This ensure the CRDs are deployed first, before the helm chart (or a wrapper helm chart) creates any CRs.

Reference docs
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

Also  remove templates from crds.yaml since i expect labels to be of lesser value on CRDs then the proper deployment of those.

### CODE REVIEW

**Comment by EugenMayer** [comment]
Needs to be discussed since the CRDs are yet requiring templates (labels). What is the actual use of labels on CRDs? Is there a real use for that - since this would be a blocker for deploying the CRDs the proper helm way

**Comment by EugenMayer** [comment]
Any chance to get an answer on this. This PR might look big, but it is not - just moving files without touching them except:

 - remove ability to dynamically label CRDs since this would require gotpl which would block the usage of the CRD deployment

Thanks!

**Comment by innobead** [comment]
I believe we visited this before but had some concerns. cc @jenting

**Comment by jenting** [comment]
Thanks for your PR @EugenMayer 

However, the helm does not handle the upgrade CRD if you put the CRD manifest into the `crds/` folder.
That's _why_ we keep the CRD manifest inside the `template/` folder.

**Comment by EugenMayer** [comment]
@jenting thanks for the follow up. Interesting point, i'am entirely unaware, could you explain or link docs for that?

AFAIU deploying the CRDs from the /crd folder on day,

a) then updating one CRD in `/crd/foo.yml` 
b) adding a new CRD in `crd/bar.yml`

And then redeploying on existing chart installation will not reapply / change those CRDS / add that CRD?

Could you explain if both cases are problematic, a) and b)? Somewhat i assume a) to be problematic in itself and should most probably never be done. Rather using a new CRD with v2..v3 .. but if b) is not working etiher, i understand that this is a huge issue.

Thanks for you time!

**Comment by jenting** [comment]
> @jenting thanks for the follow up. Interesting point, i'am entirely unaware, could you explain or link docs for that?

You could follow this issue https://github.com/longhorn/longhorn/pull/3224

> AFAIU deploying the CRDs from the /crd folder on day,
> 
> a) then updating one CRD in `/crd/foo.yml` b) adding a new CRD in `crd/bar.yml`
> 
> And then redeploying on existing chart installation will not reapply / change those CRDS / add that CRD?

You could try add some change on one of the CRD yaml manifest like `crds/foo.yml`, and then run `helm upgrade`. You could see that the updated `crds/foo.yml` won't be reflected in the cluster.

> 
> Could you explain if both cases are problematic, a) and b)? Somewhat i assume a) to be problematic in itself and should most probably never be done. Rather using a new CRD with v2..v3 .. but if b) is not working etiher, i understand that this is a huge issue.
> 
> Thanks for you time!

**Comment by jenting** [comment]
Besides that, if you're interested in contributing the helm chart enhancement, please file the PR to [here](https://github.com/longhorn/longhorn/tree/master/chart)?
Because this repo is mirrored from the https://github.com/longhorn/longhorn/tree/master/chart, thank you.

**Comment by EugenMayer** [comment]
That is a shocker. Is this really intended by helm chart or a known bug to be fixed? It really seems that the entire CRD topic has not be tough through in the deployment phase, just the API level / meta-model seems to be well designed and flexible. But when it comes to deploy them, within a helmchart for the app you are currently deploing, or even updating them, it all falls apart. Similar issues in terraform with the kubernetes_manifest resource.

So bottom line, using `/crd` is even worse then deploying CRDs as normal templates, since the former is not only not updateable (which i could understand, that deployed CRDs are immutable), but even adding new ones is not possible.

I guess opening a PR on https://github.com/longhorn/longhorn/tree/master/chart will not make any sense, i think your arguments really are more then good enough to use the "better worse". So from my POV, first of thank you for explaining, second i guess we can close the PR?

**Comment by jenting** [comment]
Yes, as far as I know, helm does not handle CRD upgrade in helm 2 _or_ helm 3.

According to helm best practice, the best approach is to separate the CRD into another chart at day 1.
If it does not separate at day 1, the current way/workaround we found is to keep the CRD manifest inside the `templates/` folder and helm install/upgrade will make sure all the resources inside the `templates/` folder will be applied/updated.

And, we have to make sure the CR is applied/updated after the CRD manifests are applied/updated, we could achieve this by helm hooks. You could refer to how to tackle this for Longhorn v1.3.0 https://github.com/longhorn/longhorn/blob/251789f/chart/templates/customize-default-setting.yaml#L6-L7.

Last but not least, I think this PR could be closed because I tried this approach before but it's not working for helm upgrade not upgrading the CRD manifest.

**Comment by EugenMayer** [comment]
Full ack, close anytime.

**Comment by innobead** [comment]
ref: exactly like @jenting described, https://github.com/helm/helm/issues/6581

Let's close this first, but thanks @EugenMayer contribution 👍

**Pull request closed without merging**
