### PR TITLE
fix: update version number as 1.2.6 in question.yaml

### PR DESCRIPTION
**Pull request by weizhe0422**
Signed-off-by: Ray Chang <ray.chang@suse.com>

### CODE REVIEW

**Review by PhanLe1010 — CHANGES_REQUESTED** [review]
This one should be `v3.2.1`

```
  - variable: image.csi.attacher.tag
    default: v3.4.0
```

**Comment by weizhe0422** [comment]
@PhanLe1010 I have fixed the tag of csi-attacher. Thank you.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
It was missed, this also needed to fix in longhorn repo.

**Review by innobead — COMMENTED** [review]
Wait why we updated versions of attacher and node driver?

https://github.com/longhorn/longhorn/commit/80a7ea47e1dafb96f7122f8d220d2bbcde85c995

**Comment by weizhe0422** [comment]
I update the versions which is referenced from [longhorn-images.txt](https://github.com/longhorn/longhorn/blob/v1.2.x/deploy/longhorn-images.txt). 

Do I need to roll back the versions of attacher and node driver?

**Comment by innobead** [comment]
I think YES, the image txt seems not be updated correctly, so u need to update the image.txt in longhorn and longhorn-manager repos, but questions only in longhorn repo.

cc @PhanLe1010

**Comment by PhanLe1010** [comment]
I think the current [longhorn-images.txt](https://github.com/longhorn/longhorn/blob/v1.2.x/deploy/longhorn-images.txt) is correct. This is for Longhorn 1.2.x so it is not outdated. 

Longhorn 1.3.x has newer [images](https://github.com/longhorn/longhorn/blob/v1.3.x/deploy/longhorn-images.txt)
Longhorn master-head has latest [images](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn-images.txt)

**Comment by innobead** [comment]
@PhanLe1010 Then this was a wrong update to 1.2 https://github.com/longhorn/longhorn/commit/80a7ea47e1dafb96f7122f8d220d2bbcde85c995?

**Comment by PhanLe1010** [comment]
@innobead Yeah, I made mistake on that commit. This backport shouldn't happen in the first place https://github.com/longhorn/longhorn/issues/4671

**Comment by innobead** [comment]
Ah it has been clarified, but actually it was missed in review as well. Let's just clarify because it has no hurt for upstream chart 🙂

**Comment by PhanLe1010** [comment]
Yeah, it is lucky that this questions.yaml has no effect on the upstream chart. Can we update this PR to have the correct csi images @weizhe0422 ?

**Pull request merged**
