### PR TITLE
Add NetworkPolicies as an optional setting

### PR DESCRIPTION
**Pull request by dgiebert**
Closes: https://github.com/longhorn/longhorn/pull/5378, https://github.com/longhorn/longhorn/issues/5403

### CODE REVIEW

**Comment by ChanYiLin** [comment]
General LGTM, thanks for your contributions!
cc @PhanLe1010

**Review by ChanYiLin — APPROVED** [review]

**Comment by innobead** [comment]
@ChanYiLin This is an external contribution. Can you help verify this to see if Longhorn works as expected? Can take this time to see if these network policies behave correctly. 

cc @longhorn/qa

**Comment by ChanYiLin** [comment]
Sure, I will help testing it

**Comment by ChanYiLin** [comment]
Verified

### longhorn-manager
can only be accessed by following pods
- [x] 1. longhorn-manager
- [x] 2. longhorn-ui
- [x] 3. longhorn-csi-plugin
- [x] 4. recurring-job.longhorn.io/longhorn.io/job-task (verified that recurring job works)
- [x] 6. longhorn-driver-deployer

It cannot be accessed by following pods
- instance-manager-e/r
  - [x] verified volume create/attach/detach works
- backing-image-manager/backing-image-data-source
  - [x] verified backingimage upload/export works

Note: 
Would like to know if we should allow instance-manager and backing image related pods to access longhorn-manager?

### lonhghorn-ui
can be accessed by traefik (networkPolicies.type == "k3s")

Note:
Need to do some modification if users deploy traefik by themselves using helm
the namespace would be default

Note:
This PR is basically copy the examples to the helm chart and add an opt flag
Nothing change from this issue: https://github.com/longhorn/longhorn/issues/1805#issuecomment-964724830

cc @shuo-wu @PhanLe1010 @innobead

**Comment by dgiebert** [comment]
Should I note that the services proxy won't work out of the box to the questions.yaml?

**Comment by innobead** [comment]
> Note: Would like to know if we should allow instance-manager and backing image related pods to access longhorn-manager?

IIRC, there is no access from those components to the longhorn manager now.

**Comment by ChanYiLin** [comment]
> Should I note that the services proxy won't work out of the box to the questions.yaml?

That will be great! Thanks :)

**Comment by ChanYiLin** [comment]
> > Note: Would like to know if we should allow instance-manager and backing image related pods to access longhorn-manager?
> 
> IIRC, there is no access from those components to the longhorn manager now.

Then it should be fine to not to allow the traffic. The functions are still working as expected.

**Comment by ChanYiLin** [comment]
Looks good to me, thanks!

**Comment by innobead** [comment]
Closing this one due to admission webhook changes in 1.5. @ChanYiLin will tackle it in another PR to the longhorn/longhorn repo.

**Pull request closed without merging**
